services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
