from .registry import registry
from .tools import (
    CreateRoleTool,
    CreateCategoryTool,
    CreateChannelTool,
    DeleteChannelTool,
    DeleteRoleTool,
    AssignRoleTool,
    RemoveRoleTool,
    ListRolesTool,
    ListChannelsTool,
    ListMembersTool,
    ReadMessagesTool,
    GetServerInfoTool,
    GetAuditLogsTool,
    GetChannelInfoTool,
    GetRoleInfoTool,
    GetMemberInfoTool,
    ListGuildsTool,
    ListEmojisTool,
    ListInvitesTool,
    SendMessageTool,
    SendEmbedMessageTool,
    SendDMTool,
    GetMessageTool,
    ListPinnedMessagesTool,
    SearchMessagesTool,
    DeleteMessageTool,
    PurgeMessagesTool,
    EditMessageTool,
    UpdateRoleTool,
    UpdateChannelTool,
    MoveChannelTool,
    UpdateServerSettingsTool,
    KickMemberTool,
    BanMemberTool,
    TimeoutMemberTool,
    RemoveTimeoutTool,
    CreateWebhookTool,
    DeleteWebhookTool,
    CreateForumThreadTool,
    CreateInviteTool
)

# Register all tools
registry.register(CreateRoleTool())
registry.register(CreateCategoryTool())
registry.register(CreateChannelTool())
registry.register(DeleteChannelTool())
registry.register(DeleteRoleTool())
registry.register(AssignRoleTool())
registry.register(RemoveRoleTool())
registry.register(ListRolesTool())
registry.register(ListChannelsTool())
registry.register(ListMembersTool())
registry.register(ReadMessagesTool())
registry.register(GetServerInfoTool())
registry.register(GetAuditLogsTool())
registry.register(GetChannelInfoTool())
registry.register(GetRoleInfoTool())
registry.register(GetMemberInfoTool())
registry.register(ListGuildsTool())
registry.register(ListEmojisTool())
registry.register(ListInvitesTool())
registry.register(SendMessageTool())
registry.register(SendEmbedMessageTool())
registry.register(SendDMTool())
registry.register(GetMessageTool())
registry.register(ListPinnedMessagesTool())
registry.register(SearchMessagesTool())
registry.register(DeleteMessageTool())
registry.register(PurgeMessagesTool())
registry.register(EditMessageTool())
registry.register(UpdateRoleTool())
registry.register(UpdateChannelTool())
registry.register(MoveChannelTool())
registry.register(UpdateServerSettingsTool())
registry.register(KickMemberTool())
registry.register(BanMemberTool())
registry.register(TimeoutMemberTool())
registry.register(RemoveTimeoutTool())
registry.register(CreateWebhookTool())
registry.register(DeleteWebhookTool())
registry.register(CreateForumThreadTool())
registry.register(CreateInviteTool())

__all__ = ["registry"]
